#!/bin/ash

#Mount all drives
#mount -t tmpfs -o size=64k,mode=0755 tmpfs /dev
#mkdir /dev/pts
#mount -t devpts devpts /dev/pts
#mount -t proc proc /proc
#mount -t sysfs sysfs /sys
#echo /sbin/mdev > /proc/sys/kernel/hotplug
#mdev -s

#Prevent kernel messages to console
dmesg -n 1

#Set hostname
hostname -F /etc/hostname

#Empty temp and run dirs
rm -rf /tmp/*
rm -rf /var/run/*

#Start system logger
syslogd -O /var/log/syslog

#Start kernel logger
klogd

#Mount proc and sys filesystems
mount -t proc none /proc
mount -t sysfs none /sys

#Mount cgroup
mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup
for sys in $(awk '!/^#/ { if ($4 == 1) print $1 }' /proc/cgroups); do
	mkdir -p "/sys/fs/cgroup/$sys"
	mount -n -t cgroup -o $sys cgroup "/sys/fs/cgroup/$sys"
done

#Enable cgroups memory hierarchy
echo 1 > /sys/fs/cgroup/memory/memory.use_hierarchy

#Set screen brightness to maximum
echo 4095 > /sys/class/backlight/backlight/brightness

#Print system log to tty10 (ALT+F10)
tail -f /var/log/syslog > /dev/tty10 &

#Load modules for auto-detected hardware
grep -h MODALIAS /sys/bus/*/devices/*/uevent 2> /dev/null | cut -d= -f2 | sort -u | xargs modprobe -abq 2> /dev/null

#Start cron daemon
crond -c /etc/crond

#Start all network interfaces
ifup -a
